color_list = [
	'Black',
	'Brown',
	'Yellow',
	'Green',
	'Silver',
	'White',
	'Orange',
	'Red',
	'Blue',
	'Gold',
	'Purple',
	'Pink',
	'Multi-color',
]


idea_list = [
	'New Arrivals',
	'Hottest Designs',
	'Flowers',
	'Skulls',
	'Hearts',
	'Vintage',
	'Animals',
	'Abstract',
	'Snazzy',
	'Black & White',
	'Pattern & Textures',
	'Orient',
	'Funny',
	'Colorful',
	'Urban',
	'Other',
]

products_only_list = [
	'Abstract Flowers and Feathers',
	'Abstract Wall',
	'Ace of Spades',
	'African Elephant',
	'All Seeing Eye',
	'Bed of Roses',
	'Bleeding Hearts',
	'Blessed Virgin',
	'Brasilian',
	'Bridal Bouquet',
	'Bunch of Flowers',
	'Calfornia Republic',
	'Camo',
	'Cherry Blossoms',
	'Circuit Board',
	'Colorful Heart Collage',
	'Creepy Lab',
	'Crisp Air',
	'Danger Zone',
	'Day in Egypt',
	'Dia de los Muertes',
	'Diamond Plate',
	"Don't Worry Be Happy (Black)",
	"Don't Worry Be Happy (White)",
	'Elegant Flowers',
	'Enjoy the Sea',
	'Eye of the Tiger',
	'Faded Bouquet Print',
	'Fleur De Lis',
	'Floral Ornament',
	'Flower Skull',
	'Flower Tattoo',
	'Flowers and Butterflies',
	'Gold Fish',
	'Golden Feather',
	'Got Beer?',
	'Graffiti Covered Wall',
	'Hand Drawn Flower',
	'Hearts with Love',
	'Hippie Flowers',
	'Hipster Doodle Monster Collage',
	'I LOVE BRA',
	'I LOVE UK',
	'I LOVE USA',
	'Japanese Flower Field',
	'KICK YOUR ASS',
	'Keep Calm and Carry On',
	'Leopard',
	'Long Live the Queen',
	'Looking for Flowers',
	'Marine Stripe',
	'Midnight Visitor',
	'Moonlit Night',
	'Mosaic',
	'OMG',
	'Obituary',
	'One Bite Leads to Another',
	'Oriental Dragon',
	'Ornamental Skulls',
	'Over the Rainbow',
	'Painted Leopard',
	'Paisley Butterfly',
	'Paisley Heart',
	'Paisley Monochrome',
	'Peace and Colors',
	'Pray for Peace',
	'Psychedelic Explosion',
	'Radar Map',
	'Raining Hearts',
	'Retro Camera',
	'Rise Up',
	'Royal Soul',
	'Rusty Wall',
	'Sailor Royalty',
	'Samurai Warriors',
	'Skull Republic',
	'Skulls with Roses',
	'Snakeskin',
	'Snazzy Giraffe',
	'Snazzy Zebra',
	'Solid Black',
	'Solid White',
	'Statue of Liberty',
	'Stipe Overload',
	'Studs',
	'The Great Wave',
	'The King',
	'Tropical Flowers',
	'US Flag',
	'Union Jack',
	'Vintage Carnation',
	'Vintage Hibiscus',
	'Vintage Jeans',
	'Vintage Roses on Navy',
	'Vintage Roses on Pink',
	'Vintage World Map',
	'Vintange Koleidoscope',
	'Vivid Flowers',
	'Whooo Whooo',
	'Yin Yang'
]

ideas_n_products_list = [
	('Hottest Designs', 'Cherry Blossoms'),
	('Hottest Designs', 'Bed of Roses'),
	('Hottest Designs', 'Bunch of Flowers'),
	('Hottest Designs', 'Flowers and Butterflies'),
	('Hottest Designs', 'Dia de los Muertes'),
	('Hottest Designs', 'Obituary'),
	('Hottest Designs', 'Creepy Lab'),
	('Hottest Designs', 'Ace of Spades'),
	('Hottest Designs', 'Royal Soul'),
	('Hottest Designs', 'Long Live the Queen'),
	('Hottest Designs', 'All Seeing Eye'),
	('Hottest Designs', 'One Bite Leads to Another'),
	('Hottest Designs', 'KICK YOUR ASS'),
	('Hottest Designs', 'Studs'),
	('Hottest Designs', 'Diamond Plate'),
	('Hottest Designs', 'Circuit Board '),
	('Hottest Designs', 'Psychedelic Explosion'),
	('Hottest Designs', "Don't Worry Be Happy (Black)"),
	('Hottest Designs', "Don't Worry Be Happy (White)"),
	('Hottest Designs', 'Abstract Flowers and Feathers'),
	('Hottest Designs', 'Blessed Virgin'),
	('Hottest Designs', 'Pray for Peace'),
	('Hottest Designs', 'Oriental Dragon '),
	('Hottest Designs', 'Yin Yang'),
	('Hottest Designs', 'Eye of the Tiger'),
	('Hottest Designs', 'The King'),
	('Hottest Designs', 'Snazzy Zebra'),
	('Hottest Designs', 'Leopard'),
	('Hottest Designs', 'Snazzy Giraffe'),
	('Hottest Designs', 'OMG'),
	('Hottest Designs', 'Fleur De Lis'),
	('Hottest Designs', 'Colorful Heart Collage'),
	('Hottest Designs', 'Paisley Heart'),
	('Hottest Designs', 'Marine Stripe'),
	('Hottest Designs', 'Sailor Royalty'),
	('Hottest Designs', 'Rusty Wall'),
	('Hottest Designs', 'Keep Calm and Carry On'),
	('Hottest Designs', 'Rise Up'),
	('Hottest Designs', 'The Great Wave'),
	('Hottest Designs', 'I LOVE USA'),
	('Hottest Designs', 'I LOVE UK'),
	('Hottest Designs', 'I LOVE BRA'),
	('Flowers', 'Cherry Blossoms'),
	('Flowers', 'Hand Drawn Flower'),
	('Flowers', 'Bridal Bouquet '),
	('Flowers', 'Vivid Flowers'),
	('Flowers', 'Vintage Hibiscus'),
	('Flowers', 'Bed of Roses'),
	('Flowers', 'Bunch of Flowers'),
	('Flowers', 'Floral Ornament'),
	('Flowers', 'Vintage Roses on Pink'),
	('Flowers', 'Flowers and Butterflies'),
	('Flowers', 'Elegant Flowers'),
	('Flowers', 'Vintage Roses on Navy'),
	('Flowers', 'Vintage Carnation'),
	('Flowers', 'Tropical Flowers'),
	('Flowers', 'Looking for Flowers'),
	('Flowers', 'Skulls with Roses'),
	('Flowers', 'Long Live the Queen'),
	('Flowers', 'Abstract Flowers and Feathers'),
	('Flowers', 'Paisley Monochrome'),
	('Flowers', 'Flower Tattoo'),
	('Flowers', 'Hippie Flowers'),
	('Skulls', 'Flower Skull'),
	('Skulls', 'Ornamental Skulls'),
	('Skulls', 'Skulls with Roses'),
	('Skulls', 'Dia de los Muertes'),
	('Skulls', 'Obituary'),
	('Skulls', 'Creepy Lab'),
	('Skulls', 'Long Live the Queen'),
	('Skulls', 'Skull Republic'),
	('Hearts', 'Paisley Butterfly'),
	('Hearts', 'Enjoy the Sea'),
	('Hearts', 'Whooo Whooo'),
	('Hearts', 'Bleeding Hearts'),
	('Hearts', 'Raining Hearts'),
	('Hearts', 'Colorful Heart Collage'),
	('Hearts', 'Hearts with Love'),
	('Hearts', 'Paisley Heart'),
	('Vintage', 'Hand Drawn Flower'),
	('Vintage', 'Vivid Flowers'),
	('Vintage', 'Vintage Roses on Pink'),
	('Vintage', 'Elegant Flowers'),
	('Vintage', 'Vintage Roses on Navy'),
	('Vintage', 'Vintage Carnation'),
	('Vintage', 'Tropical Flowers'),
	('Vintage', 'Abstract Wall'),
	('Vintage', 'Obituary'),
	('Vintage', 'Creepy Lab'),
	('Vintage', 'Vintage World Map'),
	('Vintage', 'Statue of Liberty'),
	('Vintage', 'Vintage Jeans'),
	('Vintage', 'Retro Camera'),
	('Vintage', 'Rise Up'),
	('Vintage', 'US Flag'),
	('Vintage', 'Union Jack'),
	('Vintage', 'Brasilian '),
	('Vintage', 'Vintange Koleidoscope'),
	('Vintage', 'Skull Republic'),
	('Animals', 'Paisley Butterfly'),
	('Animals', 'Looking for Flowers'),
	('Animals', 'Crisp Air'),
	('Animals', 'Enjoy the Sea'),
	('Animals', 'Whooo Whooo'),
	('Animals', 'Midnight Visitor'),
	('Animals', 'Painted Leopard'),
	('Animals', 'Moonlit Night'),
	('Animals', 'Oriental Dragon '),
	('Animals', 'Yin Yang'),
	('Animals', 'Eye of the Tiger'),
	('Animals', 'The King'),
	('Animals', 'Snazzy Zebra'),
	('Animals', 'Leopard'),
	('Animals', 'Snazzy Giraffe'),
	('Animals', 'Snakeskin'),
	('Animals', 'African Elephant'),
	('Animals', 'Gold Fish'),
	('Abstract', 'Abstract Wall'),
	('Abstract', 'Psychedelic Explosion'),
	('Abstract', 'Abstract Flowers and Feathers'),
	('Abstract', 'Over the Rainbow'),
	('Snazzy', 'Snazzy Zebra'),
	('Snazzy', 'Snazzy Giraffe'),
	('Black & White', 'Flower Skull'),
	('Black & White', 'Ornamental Skulls'),
	('Black & White', 'Dia de los Muertes'),
	('Black & White', 'Creepy Lab'),
	('Black & White', 'Ace of Spades'),
	('Black & White', 'All Seeing Eye'),
	('Black & White', 'One Bite Leads to Another'),
	('Black & White', 'KICK YOUR ASS'),
	('Black & White', "Don't Worry Be Happy (Black)"),
	('Black & White', 'Yin Yang'),
	('Black & White', 'Eye of the Tiger'),
	('Black & White', 'The King'),
	('Black & White', 'Snazzy Zebra'),
	('Black & White', 'Fleur De Lis'),
	('Black & White', 'Solid Black '),
	('Black & White', 'Solid White'),
	('Black & White', 'Paisley Monochrome'),
	('Pattern & Textures', 'Cherry Blossoms'),
	('Pattern & Textures', 'Hand Drawn Flower'),
	('Pattern & Textures', 'Bunch of Flowers'),
	('Pattern & Textures', 'Floral Ornament'),
	('Pattern & Textures', 'Vintage Roses on Pink'),
	('Pattern & Textures', 'Flowers and Butterflies'),
	('Pattern & Textures', 'Elegant Flowers'),
	('Pattern & Textures', 'Vintage Roses on Navy'),
	('Pattern & Textures', 'Whooo Whooo'),
	('Pattern & Textures', 'Painted Leopard'),
	('Pattern & Textures', 'Peace and Colors'),
	('Pattern & Textures', 'Ornamental Skulls'),
	('Pattern & Textures', 'Skulls with Roses'),
	('Pattern & Textures', 'Studs'),
	('Pattern & Textures', 'Diamond Plate'),
	('Pattern & Textures', 'Camo'),
	('Pattern & Textures', "Don't Worry Be Happy (Black)"),
	('Pattern & Textures', "Don't Worry Be Happy (White)"),
	('Pattern & Textures', 'Over the Rainbow'),
	('Pattern & Textures', 'Snazzy Zebra'),
	('Pattern & Textures', 'Leopard'),
	('Pattern & Textures', 'Snazzy Giraffe'),
	('Pattern & Textures', 'Snakeskin'),
	('Pattern & Textures', 'Bleeding Hearts'),
	('Pattern & Textures', 'Raining Hearts'),
	('Pattern & Textures', 'Colorful Heart Collage'),
	('Pattern & Textures', 'Hearts with Love'),
	('Pattern & Textures', 'Stipe Overload'),
	('Pattern & Textures', 'Day in Egypt'),
	('Pattern & Textures', 'African Elephant'),
	('Pattern & Textures', 'Paisley Monochrome'),
	('Pattern & Textures', 'Mosaic'),
	('Pattern & Textures', 'Vintange Koleidoscope'),
	('Orient', 'Cherry Blossoms'),
	('Orient', 'Samurai Warriors'),
	('Orient', 'Oriental Dragon '),
	('Orient', 'Yin Yang'),
	('Orient', 'Gold Fish'),
	('Orient', 'Japanese Flower Field'),
	('Orient', 'Faded Bouquet Print'),
	('Orient', 'The Great Wave'),
	('Funny', 'One Bite Leads to Another'),
	('Funny', 'KICK YOUR ASS'),
	('Funny', 'Snazzy Zebra'),
	('Funny', 'Snazzy Giraffe'),
	('Funny', 'OMG'),
	('Funny', 'Got Beer?'),
	('Colorful', 'Hand Drawn Flower'),
	('Colorful', 'Bridal Bouquet '),
	('Colorful', 'Vivid Flowers'),
	('Colorful', 'Bed of Roses'),
	('Colorful', 'Bunch of Flowers'),
	('Colorful', 'Tropical Flowers'),
	('Colorful', 'Paisley Butterfly'),
	('Colorful', 'Looking for Flowers'),
	('Colorful', 'Crisp Air'),
	('Colorful', 'Enjoy the Sea'),
	('Colorful', 'Whooo Whooo'),
	('Colorful', 'Painted Leopard'),
	('Colorful', 'Peace and Colors'),
	('Colorful', 'Abstract Wall'),
	('Colorful', 'Psychedelic Explosion'),
	('Colorful', 'Graffiti Covered Wall'),
	('Colorful', 'Abstract Flowers and Feathers'),
	('Colorful', 'Hipster Doodle Monster Collage'),
	('Colorful', 'Over the Rainbow'),
	('Colorful', 'Samurai Warriors'),
	('Colorful', 'Oriental Dragon '),
	('Colorful', 'OMG'),
	('Colorful', 'Colorful Heart Collage'),
	('Colorful', 'Stipe Overload'),
	('Colorful', 'Golden Feather'),
	('Colorful', 'Hippie Flowers'),
	('Colorful', 'Mosaic'),
	('Colorful', 'Japanese Flower Field'),
	('Urban', 'Painted Leopard'),
	('Urban', 'Flower Skull'),
	('Urban', 'Obituary'),
	('Urban', 'Creepy Lab'),
	('Urban', 'Ace of Spades'),
	('Urban', 'Royal Soul'),
	('Urban', 'Long Live the Queen'),
	('Urban', 'All Seeing Eye'),
	('Urban', 'One Bite Leads to Another'),
	('Urban', 'KICK YOUR ASS'),
	('Urban', 'Studs'),
	('Urban', 'Diamond Plate'),
	('Urban', 'Circuit Board '),
	('Urban', 'Vintage World Map'),
	('Urban', 'Radar Map'),
	('Urban', 'Statue of Liberty'),
	('Urban', 'Eye of the Tiger'),
	('Urban', 'The King'),
	('Urban', 'Snazzy Zebra'),
	('Urban', 'Leopard'),
	('Urban', 'Snazzy Giraffe'),
	('Urban', 'OMG'),
	('Urban', 'Fleur De Lis'),
	('Urban', 'Danger Zone'),
	('Urban', 'Stipe Overload'),
	('Urban', 'Rusty Wall'),
	('Urban', 'Keep Calm and Carry On')
]

color_list_products = [
	('Black', 'Ornamental Skulls'),
	('Black', 'Dia de los Muertes'),
	('Black', 'Creepy Lab'),
	('Black', 'Ace of Spades'),
	('Black', 'All Seeing Eye'),
	('Black', 'One Bite Leads to Another'),
	('Black', "Don't Worry Be Happy (Black)"),
	('Black', 'Tribal Cross'),
	('Black', 'Yin Yang'),
	('Black', 'The King'),
	('Black', 'Snazzy Zebra'),
	('Black', 'Fleur De Lis'),
	('Black', 'Flower Tattoo'),
	('Black', 'Solid Black'),
	('Black', 'Retro Camera'),
	('Black', 'Paisley Monochrome'),
	('Black', 'I LOVE USA'),
	('Black', 'I LOVE UK'),
	('Black', 'I LOVE BR'),
	('Black', 'Calfornia Republic'),
	('Brown', 'Floral Ornament'),
	('Brown', 'Obituary'),
	('Brown', 'Leopard'),
	('Brown', 'Snazzy Giraffe'),
	('Brown', 'Snakeskin'),
	('Brown', 'Day in Egypt'),
	('Yellow', 'Vivid Flowers'),
	('Yellow', 'Flowers and Butterflies'),
	('Yellow', 'Snazzy Giraffe'),
	('Yellow', 'Danger Zone'),
	('Yellow', 'Rise Up'),
	('Yellow', 'Gold Fish'),
	('Green', 'Looking for Flowers'),
	('Green', 'Camo'),
	('Green', "Don't Worry Be Happy (White)"),
	('Green', 'Brasilian '),
	('Silver', 'Studs'),
	('Silver', 'Diamond Plate'),
	('Silver', 'Rusty Wall'),
	('White', 'Flower Skull'),
	('White', 'Ace of Spades'),
	('White', 'Royal Soul'),
	('White', 'Long Live the Queen'),
	('White', 'KICK YOUR ASS'),
	('White', "Don't Worry Be Happy (White)"),
	('White', 'Yin Yang'),
	('White', 'Eye of the Tiger'),
	('White', 'Snazzy Zebra'),
	('White', 'Solid White'),
	('White', 'African Elephant'),
	('Orange', 'Pray for Peace'),
	('Orange', 'Got Beer?'),
	('Red', 'Bed of Roses'),
	('Red', 'Flowers and Butterflies'),
	('Red', 'Vintage Carnation'),
	('Red', 'Skulls with Roses'),
	('Red', 'Statue of Liberty'),
	('Red', 'Marine Stripe'),
	('Red', 'Keep Calm and Carry On'),
	('Red', 'US Flag'),
	('Red', 'Union Jack'),
	('Red', 'Skull Republic'),
	('Blue', 'Elegant Flowers'),
	('Blue', 'Vintage Roses on Navy'),
	('Blue', 'Crisp Air'),
	('Blue', 'Enjoy the Sea'),
	('Blue', 'Midnight Visitor'),
	('Blue', 'Moonlit Night'),
	('Blue', 'Circuit Board '),
	('Blue', 'Radar Map'),
	('Blue', 'Statue of Liberty'),
	('Blue', 'Vintage Jeans'),
	('Blue', 'Marine Stripe'),
	('Blue', 'Sailor Royalty'),
	('Blue', 'US Flag'),
	('Blue', 'Union Jack'),
	('Blue', 'Vintange Koleidoscope'),
	('Blue', 'The Great Wave'),
	('Purple', 'Bridal Bouquet'),
	('Purple', 'Vintage Hibiscus'),
	('Purple', 'Japanese Flower Field'),
	('Pink', 'Cherry Blossoms'),
	('Pink', 'Bridal Bouquet'),
	('Pink', 'Vintage Roses on Pink'),
	('Pink', 'Tropical Flowers'),
	('Pink', 'Raining Hearts'),
	('Pink', 'Hearts with Love'),
	('Pink', 'Paisley Heart'),
	('Multi-color', 'Hand Drawn Flower'),
	('Multi-color', 'Bunch of Flowers'),
	('Multi-color', 'Paisley Butterfly'),
	('Multi-color', 'Whooo Whooo'),
	('Multi-color', 'Painted Leopard'),
	('Multi-color', 'Peace and Colors'),
	('Multi-color', 'Abstract Wall'),
	('Multi-color', 'Vintage World Map'),
	('Multi-color', 'Psychedelic Explosion'),
	('Multi-color', 'Graffiti Covered Wall'),
	('Multi-color', 'Abstract Flowers and Feathers'),
	('Multi-color', 'Hipster Doodle Monster Collage'),
	('Multi-color', 'Over the Rainbow'),
	('Multi-color', 'Samurai Warriors'),
	('Multi-color', 'Oriental Dragon '),
	('Multi-color', 'OMG'),
	('Multi-color', 'Bleeding Hearts'),
	('Multi-color', 'Colorful Heart Collage'),
	('Multi-color', 'Stipe Overload'),
	('Multi-color', 'Golden Feather'),
	('Multi-color', 'Hippie Flowers'),
	('Multi-color', 'Mosaic'),
	('Multi-color', 'Faded Bouquet Print'),
	('Green', 'I LOVE BRA'),
	('Black', 'Solid Black'),
	('Pink', 'Bridal Bouquet'),
	('White', 'Blessed Virgin'),
]



